ДЗ 1
LeeRoyod/2024-2-VK-EDU-Frontend-I-Surmin pull request #1
Opened 2024-09-27 14:52 UTC by LeeRoyod

# Домашнее задание №1

Прошу @martinkomitsky и@nelkor проверить его.

Что было сделано:
* Реализованы функции `convertBytesToHuman.js`, `correctSentence.js`, `nonUniqueElements.js`;
* Написан тест на функцию `convertBytesToHuman`

2024-09-30 16:14 UTC, nelkor requested changes

2024-09-30 16:14 UTC, nelkor commented on convertBytesToHuman.test.js
> +  test('Возвращает false для неправильного типа данных', () => {
Добавь проверку на `NaN`.

2024-09-30 16:14 UTC, nelkor commented on correctSentence.test.js
> +
Добавь проверки на неправильные типы данных.

2024-09-30 16:14 UTC, nelkor commented on nonUniqueElements.js
> +  const frequency = {};
Проверяй неправильные типы данных в функции и добавь проверки на них в тестах.

2024-10-02 07:02 UTC, nelkor approved these changes
Недочёты есть, но и время уже 2 октября. В целом, всё работает.

2024-10-02 21:00 UTC, HaseProgram approved these changes
Аппрув, 10!

2024-10-02 21:00 UTC, merged