ДЗ 2
LeeRoyod/2024-2-VK-EDU-Frontend-I-Surmin pull request #2
Opened 2024-09-30 19:17 UTC by LeeRoyod

Прошу @martinkomitsky или @nelkor проверить его.

Что было сделано:
* стилизована форма отправки сообщений, в меру возможности, в соответствии с макетом;
* установлены иконки material icons;
* по нажатию на кнопку Enter, сообщение сохраняются в localStorage и добавляются к списку сообщений выше;
* поле ввода очищается после нажатия на кнопку Enter;
* сообщение содержат текст, имя отправителя и время отправки;
* при обновлении страницы уже отправленные сообщения загружаются из localStorage;
* настроен деплой странички на GitHub Pages [https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/](https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/)

![SharedScreenshot1](https://github.com/user-attachments/assets/81f6eb69-4cdc-4267-b39b-6817f69891f1)

2024-10-02 12:22 UTC, nelkor requested changes
**Баги**

1. При смене ника ломается подсветка своих сообщений. Если я перезагрузил страницу и выбрал ник, под которым уже были сообщения, они тоже должны стать "моими".

2. Я выбрал ник "\<div\>" и мои сообщения стали "без имени".

2024-10-02 12:22 UTC, nelkor commented on simple-chat/package.json
> +    "webpack": "^4.41.0",
Эта версия webpack вышла 5 лет назад. Современная версия — 5.95.0. Гипотетически, можно и оставить, но при решение вообще какой угодно задачи не стоит пользовать настолько устаревшими версиями инструментов.

2024-10-02 12:22 UTC, nelkor commented on simple-chat/src/index.js
> +    form.addEventListener('keypress', function (event) {
Форма ведь и так по нажатию Enter `submit` должна получать?

2024-10-06 11:06 UTC, nelkor approved these changes

2024-10-07 19:51 UTC, martinkomitsky commented
12!

2024-10-07 19:51 UTC, merged