ДЗ 7
LeeRoyod/2024-2-VK-EDU-Frontend-I-Surmin pull request #7
Opened 2024-11-07 18:30 UTC by LeeRoyod

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.
GitHub Pages [https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/](https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/)

Что было сделано:
* Используется [backend](https://github.com/education-vk-company/vk-edu-messenger-backend/tree/main);
* Созданы окна для регистрации и авторизации;
* Интегрирован API:
  - Отправка/получение/редактирование/удаление сообщений;
  - Регистрация/авторизация/изменение пользователей;
  - Создание/удаление/получение чатов.

2024-11-11 11:17 UTC, nelkor requested changes
В целом, всё хорошо, всё работает, но пришло время задуматься об архитектуре приложения. Пусть всем, что относится к запросам к серверу, отвечает отдельный модуль. Он будет хранить access_token, и передавать все нужные параметры в запросы, а компоненты будут просто использовать функции для получения и сохранения данных.

2024-11-11 11:17 UTC, nelkor commented on react-chat/src/App.jsx
> +            const response = await fetch(`${process.env.REACT_APP_API_URL}/user/current/`, {
Следует вынести логику запросов из компонентов. Проанализируй все запросы, которые делает приложение, и создай отдельный модуль (директорию), который экспортирует функции под каждый из этих случаев. Например, `loadMessages`, `sendMessage` и так далее.

2024-11-18 10:40 UTC, nelkor requested changes
Сейчас заметил, что используешь `export default` много где. Надо везде их убрать. Плюс маленькая правка по файлу с api-функциями.

2024-11-18 10:40 UTC, nelkor commented on react-chat/src/api/api.js
> +export default Api;
Не используем `export default`. Сразу при объявлении можно написать `export`.

2024-11-18 10:40 UTC, nelkor commented on react-chat/src/App.jsx
> +import Api from './api/api';
Если файл будет называться `index.js`, то можно будет импортировать из `api`, а не из `api/api`.

```suggestion
import { Api } from './api';
```

2024-11-20 12:32 UTC, nelkor approved these changes

2024-11-24 11:54 UTC, merged

2024-11-24 11:55 UTC, martinkomitsky commented
12!