ДЗ 8
LeeRoyod/2024-2-VK-EDU-Frontend-I-Surmin pull request #8
Opened 2024-12-06 17:13 UTC by LeeRoyod

# Домашнее задание №8

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor проверить его.
GitHub Pages [https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/](https://leeroyod.github.io/2024-2-VK-EDU-Frontend-I-Surmin/)

Что было сделано:
* Реализована отправка координат пользователя используя Geolocation API;
* Реализована отправка картинок;
* Реализована запись и отправка голосовых сообщений;
* Реализованы уведомления при получении сообщений из соседних чатов.

2024-12-09 07:36 UTC, nelkor requested changes
В целом, всё хорошо. Есть визуальные баги с миганием при переходе между экранами.

Если открыть окно "Создать новый чат", написать что-нибудь в фильтре, а потом нажать "Отмена", окно мигнёт перед тем, как исчезнуть.

Ну и плюс небольшая правка по архитектуре. Логика работы с сетью строго должна быть в отдельном слое, компоненты должны лишь использовать экспортируемые функции.

2024-12-09 07:36 UTC, nelkor commented on react-chat/src/App.jsx
> +                                fetch('/api/centrifugo/connect/', {
Всю работу с `centrifugo` также необходимо вынести в `api`. Для компонента это слишком низкоуровневая логика.

2024-12-09 07:36 UTC, nelkor commented on react-chat/src/api/index.js
> +    const sendMessage = async (messageData, isFormData = false) => {
Можно в этой же функции производить проверку:
`messageData instanceof FormData`

Иначе может возникать парадокс, если передать в функцию FormData, но не передать второй аргумент.

2024-12-16 10:04 UTC, nelkor approved these changes

2024-12-17 10:41 UTC, merged

2024-12-17 10:41 UTC, martinkomitsky commented
7